### ISSUE TITLE
Change Page buttons break when recipe book is open

### ISSUE THREAD

**Issue by mjwells2002** [Andrew6rant/InventoryTabs#1]
when recipe book is open and tab switching buttons are on screen the buttons are in the wrong place
![image](https://user-images.githubusercontent.com/36360408/156759173-01fefc73-69c3-4c7e-b548-4889e704dba0.png)

**Comment by Andrew6rant** [comment]
Oops! I never use the recipe book, so I completely overlooked this. Shouldn't be difficult to implement, as I already have the logic to shift the tab render over.

**Comment by qualterz** [comment]
It looks like this [commit](https://github.com/Andrew6rant/inventorytabs/commit/f54bbddc7716b0dce90a1751eed41b787e02e9bc) fixes this bug. Should this issue be closed?

**Comment by Andrew6rant** [comment]
I held off on releasing a new update, because the offset buttons overlap with REI (if it is installed). I was planning on adding a REI plugin to provide an exclusion zone, but I really haven't had the time to work at all on modding recently.

I've pushed a new version with the button offsets and your 1.18.2 patch (0.4.4). I'll get around to writing the REI plugin later, most people use either REI or the recipe book so I don't think it is such a big deal.
