### ISSUE TITLE
[Feature Suggestion] Crafting tab when crafting table is in inventory

### ISSUE THREAD

**Issue by Balakay420** [Andrew6rant/InventoryTabs#20]
adds portable crafting
add ability to keybind aswell?

**Comment by Andrew6rant** [comment]
I want to make sure InventoryTabs stays client-sided, so this feature is out of scope for the mod. Compatibility with an existing portable crafting mod would be cool though, I am looking into supporting those.

**Comment by sleepingdragoninn** [comment]
@Balakay420 We're looking to make this integration with [Portable Crafting Standalone](https://modrinth.com/mod/portable-crafting-standalone) just using a custom tab. 

We've managed to make clicking the tab work just fine, but getting the handled screen to update the tabmanager / support being opened via hotkey is proving a bit beyond our scope of knowledge so far (but we'll keep poking)

@Andrew6rant if you want to hit us up about this on quiltcomm/discord for any reason feel free.

**Comment by Balakay420** [comment]
@sisby-folk you wouldn't happen to have a fabric version would you?

**Comment by Balakay420** [comment]
@Andrew6rant If theres a way you could do with with Charm, that would be great

**Comment by sleepingdragoninn** [comment]
Unfortunately not! But if nothing in your modlist is in the [Quilt Mod Incompatibility Megathread](https://forum.quiltmc.org/t/mod-incompatibility-megathread/) you can use Quilt+QFAPI.

**Comment by sleepingdragoninn** [comment]
Charms full module already has a dedicated GUI button to open the crafting table, so IMO the integration should be on their end if they want it, as not to double up - open an issue there if you want. It's not like the UI there _doesn't_ work already. You just can't swap as smoothly as with pure tabs.

**Comment by Andrew6rant** [comment]
Right now, a lot of InventoryTabs' code relies on the assumption that tabs are associated with blocks in-world. I'm planning on rewriting a decent chunk of code to support entity inventories (like hopper minecarts and llama/mule chests), and to hopefully allow for tabs based on inventory items (like Portable Crafting Standalone, On A Stick, CraftingPad, etc)

**Comment by sleepingdragoninn** [comment]
Updating this (because we forgot about it) the feature for [Portable Crafting Standalone](https://modrinth.com/mod/portable-crafting-standalone) to integrate with inventory tabs has been done for a while

![image](https://user-images.githubusercontent.com/55819817/183788337-7e7f8979-ca8a-4799-a03a-039aadcbce4f.png)

as mentioned above this requires a server mod, and inventory tabs is strictly client sided - additionally, adding the tab to our portable crafting mod was not very difficult - and I'd recommend this route to anyone making another mod.

As such I reckon this can be closed - its out of scope, and compat for this stuff is too easy to add/PR to a mod itself.

**Comment by Andrew6rant** [comment]
Yeah, I tried dynamically supporting tabs for other mods, but getting the screens to open without a player hand (and with a screen already open) was kinda difficult to implement (without desync).

I should write some additional documentation for devs to build off of InventoryTabs.
