### ISSUE TITLE
Beds creating tabs

### ISSUE THREAD

**Issue by Adzetko** [Andrew6rant/InventoryTabs#31]
I don't think that's a wanted behavior, but when I open my barrel next to my beds, they appear in this mod's tabs (sometimes duplicated, as noted in https://github.com/Andrew6rant/InventoryTabs/issues/30)

![image](https://user-images.githubusercontent.com/18583615/177052829-74fd2534-e79c-4398-abbd-ae4f77fd1042.png)

**Comment by Andrew6rant** [comment]
This will be fixed in the next update.

A single bed tab was originally planned to appear only when it is a valid time to sleep, but I later decided not to implement that feature as I felt InventoryTabs should be for inventories only.

I then forgot to exclude the bed block tab when I pushed to release haha

**Comment by Andrew6rant** [comment]
Fixed in 0.8.0
