### ISSUE TITLE
Config is not saving

### ISSUE THREAD

**Issue by qualterz** [Andrew6rant/InventoryTabs#34]
I added a block path to the exclude list and it is saved only for the current session, after restarting the game the changes disappear.

**Comment by Andrew6rant** [comment]
I've been wracking my head over this for days, and it turns out the JSON serializer I used does not support empty Lists. I always use GsonConfigSerializer for my configs, but this mod is one I picked up from a previous developer who was using JanksonConfigSerializer (JSON5).

This should be fixed in the next update, but your config will be reset to a different file (.json instead of .json5)

**Comment by Andrew6rant** [comment]
Fixed in 0.8.0
