### ISSUE TITLE
Toggle the rendering of the tabs

### ISSUE THREAD

**Issue by micrwvae** [Andrew6rant/InventoryTabs#58]
could you add a toggle in the config or even a hotkey to hide the tabs entirely

**Comment by Ethan23p** [comment]
This is a good solution, make it so that savvy players can press a hotkey to delete a tab they don't need; Imagine if you could hover over a tab and press 'del' to blacklist that specific block type. Possibly better would be to change to a whitelist option; vanilla containers are whitelisted, then anything else can be added by pressing a new '+' button.
