### ISSUE TITLE
Some tabs are taller than others

### ISSUE THREAD

**Issue by AlexBrightwater** [Andrew6rant/InventoryTabs#68]
Some tabs are taller than others. It would be cool if their sizes could be unified.

Images:
[image 1](https://media.essential.gg/3e45254e-43e2-4422-b87c-f63749619800)
[image 2](https://media.essential.gg/13170294-2f2b-4ed2-b5ed-fb59bd199b00)

**Comment by Andrew6rant** [comment]
I'm sorry, I'm not exactly sure what you are asking.

Inventory Tabs are styled like the creative inventory tabs, they get taller when selected. You can use a resource pack to change this

**Comment by AlexBrightwater** [comment]
The rest of the inventory is also moving down.

**Comment by Andrew6rant** [comment]
Ooh! Yeah the tabs move according to the inventory's GUI size, so things like double chests will move the tabs up more than single chests.

If I kept the top tabs static, then the bottom ones would be the ones moving. This isn't something I can really fix without making the tabs float above and below the GUI (instead of being connected to it).

You can use the tab and shift-tab keybinds (these are configurable) to switch tabs without having to click on the moving tab locations.

I'll look into seeing if I can find a way for them to be static
